### PR TITLE
[#183] better handling of rule INPUT and OUTPUT variables

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses #183
Companion PR: irods/irods#7446
Companion PR: irods/irods#7447

TODO:
- [x] rename C++ variable `global_vars_python` (as we have decided "global" doesn't really make sense)
- [x] improve code comments
- [x] finalize name of python variable (is `irods_rule_vars` good?)
- [x] write tests
- [x] update existing tests
- update docs
    - [x] update usage of `global_vars`
    - [x] add note about deprecation of `global_vars`
- [x] open issue for eventual removal of deprecated `global_vars`
- [x] run tests

### CODE REVIEW

**Comment by trel** [comment]
nice - confirmed it works as-is by hand?

**Comment by alanking** [comment]
Is there a way to issue a `DeprecationWarning` from boost.python? Or are we just going to document the deprecation? Just curious. This is pretty neat

**Comment by SwooshyCueb** [comment]
> Is there a way to issue a `DeprecationWarning` from boost.python? Or are we just going to document the deprecation? Just curious. This is pretty neat

It's going to be a documentation-only deprecation, as there's no way (that I know of) to attach a warning to a variable in `__dict__`. We *could* write our own dict wrapper class that would throw the warning on accesses, but I think that would get rather messy rather quickly.

> nice - confirmed it works as-is by hand?

For one case, yes. I'm going to rely on the tests for the other two, but I see no reason it wouldn't work.

**Review by alanking — COMMENTED** [review]
Seems good to me. I think `irods_rule_vars` is a fine name.

**Comment by trel** [comment]
> I think irods_rule_vars is a fine name.

let's run with it.

**Review by korydraughn — COMMENTED** [review]
Agreed.

**Comment by korydraughn** [comment]
Please squash to taste and leave off the pounds.

**Comment by SwooshyCueb** [comment]
Squashed

**Review by korydraughn — APPROVED** [review]
Let's get one more approval before adding the pound.

Don't forget to check the box for `irods_rule_vars`.

**Review by trel — APPROVED** [review]
looks good

**Comment by SwooshyCueb** [comment]
Should I \# the companion PRs as well?

**Comment by trel** [comment]
i think so.   let's wait for one more set of eyes on those.

**Review by alanking — APPROVED** [review]

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
