### PR TITLE
[#227] Fix README example rule (main)

### PR DESCRIPTION
**Pull request by alanking**
Addresses #227

### CODE REVIEW

**Comment by trel** [comment]
Looks good to me.   

Any reason to add a test for anything here?
Appears to just be docs about holding it... so I'd think not...

**Review by korydraughn — APPROVED** [review]
Looks good to me.

**Comment by korydraughn** [comment]
> Any reason to add a test for anything here?
Appears to just be docs about holding it... so I'd think not...

Agreed. No need for a test.

**Comment by alanking** [comment]
Agreed. #'d, mergin

**Pull request merged**
