### PR TITLE
Added .clang-format (main)

### PR DESCRIPTION
**Pull request by korydraughn**
~Perhaps this repo continues to use spaces.~

~Will think on it.~

This project is small enough that switching to tabs is fine.

### CODE REVIEW

**Comment by korydraughn** [comment]
#'d

**Review by alanking — APPROVED** [review]
Did we need to do anything regarding tabs/spaces? This looks identical to the other .clang-format files so far...

**Comment by alanking** [comment]
No concerns here. I just noticed that this PR had a comment about tabs and yet the .clang-format file looked identical to the others. If there are no other changes needed, I will merge this.

**Comment by korydraughn** [comment]
Let's do it.

**Pull request merged**
