### PR TITLE
[irods/irods_3461] change default server SSL policy to CS_NEG_REFUSE

### PR DESCRIPTION
**Pull request by trel**
need to run through tests

### CODE REVIEW

**Review by alanking — APPROVED** [review]
Seems fine to me. @korydraughn?

**Comment by trel** [comment]
@alanking please try a test run overnight, see if it catches anything.   sorry i'm a bum.

**Comment by korydraughn** [comment]
Code change looks fine.

What @trel said :-)

**Comment by alanking** [comment]
After *14 hours* all tests passed except for one, and it is because I removed the `replNum` option from unlink, so I will fix that.

Let's # it

**Pull request merged**
