### PR TITLE
[#131] Change using to namespace for irods logger (main)

### PR DESCRIPTION
**Pull request by alanking**
Plugin now builds

### CODE REVIEW

**Comment by trel** [comment]
yeah, ship when green/ready

**Comment by alanking** [comment]
It just occurred to me that this is a divergence between what will be 4.3.1.0 and any potential 4.3.0.2. Should we make a 4-3-0-stable branch or something?

**Comment by trel** [comment]
ah, well, we can certainly do that now...    or...  we only create a branch if/when we find that we need to release a 4.3.0.2 for some reason.

**Comment by trel** [comment]
we'll just have to remember that this was a thing and that we said these smart words today

**Comment by alanking** [comment]
I think I agree with option B: create the branch when it becomes apparent that we need a 4.3.0.2. The base commit for such a branch would be 0daaa8cde8cd5cfa48f9e88ce74d818ddc373ac9.

**Pull request merged**
