### PR TITLE
prevent root ownership of paths to installed files

### PR DESCRIPTION
**Pull request by d-w-moore**
This was getting in the way of centos 7 testing of the PREP. (because /etc/irods was becoming root-owned when the PREP package was installed.)

### CODE REVIEW

**Comment by d-w-moore** [comment]
still testing, will inform when C7/PREP/postgres tests as  green .

**Comment by d-w-moore** [comment]
C7 had two failing tests but that doesn't affect this PR. ready to merge

**Comment by trel** [comment]
excellent - is there an issue number to attach here?    if not already a good one, please create one with two checkboxes.

**Comment by d-w-moore** [comment]
I'll add one if no issue yet exists for the rpm root-commandeering thing .

**Review by alanking — APPROVED** [review]

**Comment by trel** [comment]
oh dear.   merging.

**Pull request merged**
