### PR TITLE
[multiple] GCC Compatibility, Python 3 build fixes, and various housekeeping

### PR DESCRIPTION
**Pull request by SwooshyCueb**

### CODE REVIEW

**Comment by trel** [comment]
We need to bump this to `3` as well?

https://github.com/irods/irods_rule_engine_plugin_python/blob/66e0ce6926ea00751bb72093c1302d39650a712c/CMakeLists.txt#L29

**Comment by SwooshyCueb** [comment]
My goal wasn't really to get the plugin working with Python 3, but to build against libstdc++ on my machine without having to build boost against Python 2. My changes in service of 17 were to that end. So I'm not sure we're ready to bump the default up to 3, as I've done zero investigation or testing to see if further changes are needed to close out 17.

That said, while I'm working in this repo, there are a few more changes I'd like to go ahead and make in service of 17 that could be included in this PR, since it'is fresh in my mind.

**Comment by trel** [comment]
of course - go for it - this is master and will not be released until alongside 4.3.0

**Comment by d-w-moore** [comment]
Fwiw about this time last year I'd already made the changes that would both **build** and **run a rule** in python 3, so - if that's at all valuable - here's that commit: https://github.com/d-w-moore/irods_rule_engine_plugin_python/commit/3271670aa65f91a5b5bf0d60916961b045294fc6

I then did a little investigation into  packaging and how selection of python3 / boost options available on the system might work, but didn't get far at the time.

**Comment by trel** [comment]
this is now working as desired?    any input from @d-w-moore ?

**Comment by SwooshyCueb** [comment]
Currently blocked by irods/irods#5968. Can resume testing once this is fixed.

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
