### PR TITLE
[136] Set DF_1_GLOBAL flag to tell iRODS server to load plugin with RTLD_LOCAL

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses #136.
Related: irods/irods#7158
Prerequisite: irods/irods#7159

### CODE REVIEW

**Comment by SwooshyCueb** [comment]
Still running tests, but they're far enough along that I think it's safe to mark this PR as ready for review

**Review by korydraughn — COMMENTED** [review]
Looks like everything's in working order.

Do you suspect these changes will work on RHEL without issue?

**Comment by SwooshyCueb** [comment]
I don't see any reason why it wouldn't

**Review by alanking — APPROVED** [review]
Look good. We need to merge this and https://github.com/irods/irods/pull/7159 together, right?

**Comment by SwooshyCueb** [comment]
Correct

**Comment by korydraughn** [comment]
> I don't see any reason why it wouldn't

Let's confirm that one of the tests you added in this PR works for CentOS 7 or Rocky Linux.

**Comment by SwooshyCueb** [comment]
One of my tests failed in CentOS 7, as the module I was trying to import wasn't in Python yet. The others pass just fine though. I've removed the test in question.

**Comment by korydraughn** [comment]
So everything is now working for Ubuntu and CentOS now?

**Comment by SwooshyCueb** [comment]
Correct

**Review by korydraughn — APPROVED** [review]
Pound it up!

**Comment by SwooshyCueb** [comment]
\#'d

**Review by alanking — APPROVED** [review]

**Pull request merged**
