### PR TITLE
[_122] load Python3 symbols before importing core

### PR DESCRIPTION
**Pull request by d-w-moore**

### CODE REVIEW

**Comment by d-w-moore** [comment]
I know there's a better way than specifically referencing the path to the shared lib, using explicit naming and Python version.
But I don't know what that might be. @alanking @SwooshyCueb  @korydraughn

**Comment by SwooshyCueb** [comment]
Yeah this is definitely not the way to do this. This particular implementation will only work on Ubuntu 18.04 with the development package of Python 3.6 installed.

**Comment by d-w-moore** [comment]
True. However, since Ubuntu 18 is the only supported platform affected, it may be all right as a temporary solution

**Comment by alanking** [comment]
Closing in favor of #127, which includes these changes

**Pull request closed without merging**
