### PR TITLE
[#217,#218] Remove Python 2 support code, implement proper thread state handling (main)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses #217
Addresses #218 (WIP)

Not tested yet, could probably be improved.

Since I am currently testing with 4-3-stable, progress may be followed in #220 instead of in this PR.

### CODE REVIEW

**Comment by trel** [comment]
just noticing the std::lock_guard is pulled out of the try/catch, in case that's important.

**Comment by SwooshyCueb** [comment]
> just noticing the std::lock_guard is pulled out of the try/catch, in case that's important.
> 
> > 1. Throws any exceptions thrown by m.lock().

There's a reason for that. I'll probably end up moving it back in, but I need to tweak some exception handling

**Comment by SwooshyCueb** [comment]
Since I am currently testing with 4-3-stable, progress may be followed in #219 instead of in this PR.

**Comment by trel** [comment]
this is #219.   i think you're suggesting #220

**Comment by SwooshyCueb** [comment]
\#'d

**Comment by korydraughn** [comment]
Is this identical to the PR for 4-3-stable?

**Comment by SwooshyCueb** [comment]
Yes

**Review by korydraughn — APPROVED** [review]

**Review by alanking — APPROVED** [review]

**Pull request merged**
